version: '3.8'

services:
  frontend:
    container_name: drag_and_drop
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - '4000:3000'
      - '6006:6006'
